version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  spring-app:
    build: ./produit-back/
    container_name: spring-app
    depends_on:
      - mongodb
    ports:
      - "8085:8080"
    environment:
      server.port: 8080
      spring.data.mongodb.username: root
      spring.data.mongodb.password: example
      spring.data.mongodb.authentication-database: admin
      spring.data.mongodb.host: mongodb
      spring.data.mongodb.database: productDB

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

volumes:
  mongodb_data:
